extends Node
signal on_start_game;
signal on_game_over;
signal turn_page(pageId);
signal change_page(pageid);
signal pick_up_item(itemId);
signal use_item(itemId);
signal gain_character_info(infoId,characterId)
signal gain_location_info(infoId,locationId)
signal game_end(reasonId);
